/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.form;

import java.util.Arrays;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.helloweenvsfei.struts.bean.Person1;

/** 
 * MyEclipse Struts
 * Creation date: 09-09-2012
 * 
 * XDoclet definition:
 * @struts.form name="nestedTagForm"
 */
public class NestedTagForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	
	private String action;
	private Person1 person = new Person1(); // POJO 類型，這裡要先產生實體一個物件(沒有宣告 new ，則會拋出 NullPointException)
	private String [] hobby;                // 愛好hobby
	 
	
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,HttpServletRequest request) {

	  System.out.println("*********************************************");
	  System.out.println(NestedTagForm.class.getName());
	  System.out.println("action            = "+action);
	  System.out.println("person.account    = "+person.getAccount());
	  System.out.println("person.name       = "+person.getName());
	  System.out.println("person.birthday   = "+person.getBirthday());
	  System.out.println("person.secret     = "+person.isSecret());
	  System.out.println("*********************************************");
	  

	  person.setHobby(hobby!=null?Arrays.asList(hobby):Arrays.asList(new String[]{"無"}));
	  
	  
	  return null;
	} // end vaildate

	
	
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		
	} // reset



	
	
	
	
	
	
	
	
	public String getAction() {
		return action;
	}



	public void setAction(String action) {
		this.action = action;
	}



	public Person1 getPerson() {
		return person;
	}



	public void setPerson(Person1 person) {
		this.person = person;
	}



	public String[] getHobby() {
		return hobby;
	}



	public void setHobby(String[] hobby) {
		this.hobby = hobby;
	}
	
	
	
	
}