/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.form;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 06-25-2012
 * 
 * XDoclet definition:
 * @struts.form name="personForm"
 */
public class PersonForm extends ActionForm {
	
	private String action;                                  

    private Integer id;                 // id
    private String account;             // 帳號
    private String name;                // 姓名
    private String birthday;            // 生日
    private boolean secret;             // 是否隱藏姓名
    private String [] hobby;            // 愛好hobby
   

  
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	// 傳送資料時用於資料驗證
	// ActionErrors 為null 或者沒有ActionMessage 記錄，則認證通過
	// 如果ActionErrors 內有 ActionMessage 記錄，則沒有通過驗證，資料不會傳送給Action，也不會執行Action 的
	// execute()方法
	public ActionErrors validate(ActionMapping mapping,HttpServletRequest request){
	       
	  ActionErrors errors = new ActionErrors();
	  
	  System.out.println("********************************************");
	  System.out.println(PersonForm.class.getName());
	  System.out.println("01.id       = "+id);
	  System.out.println("02.account  = "+account);
	  System.out.println("03.name     = "+name);
	  System.out.println("04.birthday = "+birthday);
	  System.out.println("05.secret   = "+secret);
	  System.out.println("06.hobby    = "+Arrays.toString(hobby));
	  System.out.println("********************************************");
	  
	  
      if("add".equals(action)){  // 主要處理 增加人員
    	  
	    if(account == null || account.trim().length() == 0){
		  errors.add("account", new ActionMessage("person.error.account"));
	    }
		
	    if(name == null || name.trim().length() == 0){
		  errors.add("name", new ActionMessage("person.error.name"));
	    }
		
	    if(birthday == null || birthday.trim().length() == 0){
		  errors.add("birthday", new ActionMessage("person.error.birthday"));
	    }
			
	    if(hobby == null || hobby.length < 1){       
	      errors.add("hobby",new ActionMessage("person.error.hobby"));
	    }
	    
      }else if("list".equals(action)){  // 主要處理 列表人員
    	return null; // 直接轉到 Action execute()
      }else{}
		  
      return errors;
	}

	
	
	
	
	
	
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	// 用於重置資料(初始化資料)
	public void reset(ActionMapping mapping, HttpServletRequest request){

	}

	
	
	
	
	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	
	
	/**
	 * @return the account
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * @param account the account to set
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the birthday
	 */
	public String getBirthday() {
		return birthday;
	}

	/**
	 * @param birthday the birthday to set
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	/**
	 * @return the secret
	 */
	public boolean getSecret() {
		return secret;
	}

	/**
	 * @param secret the secret to set
	 */
	public void setSecret(boolean secret) {
		this.secret = secret;
	}

	/**
	 * @return the hobby
	 */
	public String[] getHobby() {
		return hobby;
	}

	/**
	 * @param hobby the hobby to set
	 */
	public void setHobby(String[] hobby) {
		this.hobby = hobby;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}
	

	
	
}