/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.form;

import javax.servlet.http.HttpServletRequest;


import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;


/** 
 * MyEclipse Struts
 * Creation date: 09-11-2012
 * 
 * XDoclet definition:
 * @struts.form name="vaildatorForm"
 */
public class ValidatorForm extends org.apache.struts.validator.ValidatorForm {
	/*
	 * Generated Methods
	 */

    private int age;        // ¦~ÄÖ
    private String name;    // ©m¦W
    private String email;   // email
    
    
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,HttpServletRequest request){
	
	  System.out.println("*****************************************");
	  System.out.println(ValidatorForm.class.getName());
	  System.out.println("01.age   = "+age);
	  System.out.println("02.name  = "+name);
	  System.out.println("03.email = "+email);
	  System.out.println("*****************************************");
	  
	  
	  return null;
	} // end validate
	
	
	
	

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	
	} // end reset





	public int getAge() {
	  return age;
	}
	
	public void setAge(int age) {
	  this.age = age;
	}

	public String getName() {
	  return name;
	}

	public void setName(String name) {
	  this.name = name;
	}

	public String getEmail() {
	  return email;
	}

	public void setEmail(String email) {
	  this.email = email;
	}
	
	
	
}