/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.helloweenvsfei.struts.form.HelloForm;


/** 
 * MyEclipse Struts
 * Creation date: 05-28-2012
 * 
 * XDoclet definition:
 * @struts.action path="/hello" name="helloForm" input="/form/hello.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/form/helloSuccess.jsp"
 */
public class HelloAction extends Action {
	/*
	 * Generated Methods
	 */

	
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response){
	  // 表單物件，Struts 自動為屬性給予值
	  HelloForm helloForm = (HelloForm) form;
		
	  System.out.println(HelloAction.class.getName()+" ActionForward execute() ！！！");

	  // 轉到 success 頁面，也就是 /form/helloSuccess.jsp 頁面，設定在 struts-config.xml 中
	  return mapping.findForward("success");
	}
	
	
	
}