/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.action;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.helloweenvsfei.struts.form.UploadForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-10-2012
 * 
 * XDoclet definition:
 * @struts.action path="/upload" name="uploadForm" input="/form/upload.jsp" scope="request" validate="true"
 */
public class UploadAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,HttpServletRequest request, HttpServletResponse response) throws Exception{
	  UploadForm uploadForm = (UploadForm) form;
	  
	  if("upload".equals(uploadForm.getAction())){
		return  upload(mapping,form,request,response);  
	  }
	  
	  return mapping.getInputForward();
	} // end execute
	
	
	
	
	private ActionForward upload(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response) throws Exception{
	  
	  UploadForm uploadForm = (UploadForm)form;
	  
	  StringBuffer buffer = new StringBuffer();
	  buffer.append("<style>body{ font-size:12px; }</style>");
	  
	 
	  
	  if(uploadForm.getFile()!=null && uploadForm.getFile().getFileSize() > 0 ){
		
		// 獲得資料夾  /WEB-INF/classes
		File classes = new File(getClass().getClassLoader().getResource("").getFile());
		System.out.println("k1 = "+getClass().getClassLoader().getResource("").getFile());
		//  /C:/EclipseDeveloper/MyEclipse%20Bling%20Edition%209/王者歸來%20Java%20Web%20整合開發/Apache%20Tomcat%207.0.21/webapps/struts1.2/WEB-INF/classes/

		
		// 獲得資料夾   /upload
		File uploadFolder = new File(classes.getParentFile().getParentFile(),"upload");
		uploadFolder.mkdirs();  // 建立父資料夾
		System.out.println("k2 = "+classes.getParentFile().getParentFile());
		// C:\EclipseDeveloper\MyEclipse%20Bling%20Edition%209\王者歸來%20Java%20Web%20整合開發\Apache%20Tomcat%207.0.21\webapps\struts1.2
		
		
		// 保存到 /upload 下面
		File file = new File(uploadFolder,uploadForm.getFile().getFileName());
		System.out.println("k3 = "+uploadForm.getFile().getFileName());
		// Edit2.txt
		
		
		OutputStream ous = null;  // 檔案輸出流
		InputStream ins = null;   // 上傳檔案輸入流
		try{
	      byte [] b = new byte[1024];
	      int len = 0;
	      ins = uploadForm.getFile().getInputStream();  // 上傳檔案輸入流
	      ous = new FileOutputStream(file);             // 檔案輸出流
	      while((len=ins.read(b))!=-1){
	        ous.write(b,0,len);  
	      } // end while((len=ins.read(b))!=-1){
		}catch(Exception e){
		}finally{
		  if(ins!=null) {ins.close(); ins = null; }
		  if(ous!=null) {ous.close(); ous = null; }
		}
		
		// buffer.append("檔案:<a href=upload/"+file.getName()+" target=_blank >"+file.getName()+" </a><br>");\

		String fileUploadPath = classes.getParentFile().getParentFile()+"\\upload\\"+file.getName();
		System.out.println("kevintest fileUploadPath = "+fileUploadPath);
		buffer.append("檔案:<a href="+fileUploadPath+" target=_blank  >"+file.getName()+" </a><br>");
	  }else{
		buffer.append("檔案：沒有選擇檔案<br/>");  
	  }
	  buffer.append("備註："+uploadForm.getText()+"<br>");
	  

		  
		  
	  response.setCharacterEncoding("UTF-8");
	  
	  PrintWriter out = response.getWriter();
	  out.write(buffer.toString());

	  return null;	
	} // end upload
	
	
	
}