/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.action;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.helloweenvsfei.struts.bean.Person;
import com.helloweenvsfei.struts.form.UseBeanForm;


/** 
 * MyEclipse Struts
 * Creation date: 06-04-2012
 * 
 * XDoclet definition:
 * @struts.action path="/useBean" name="useBeanForm" input="/form/useBean.jsp" scope="request" validate="true"
 */
public class UseBeanAction extends Action {
	/*
	 * Generated Methods
	 */

	
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response) throws Exception{
		
	  UseBeanForm useBeanForm = (UseBeanForm) form; 
	
	  if("add".equals(useBeanForm.getAction())){
		  
		Person person = useBeanForm.getPerson();  // 封裝好的Person
		String account = person.getAccount();
		String name = person.getName();
		
		System.out.println("*******************************************");
		System.out.println(UseBeanAction.class.getName());
		System.out.println("1.person  = "+person);
		System.out.println("2.account = "+account);
		System.out.println("3.name    = "+name);
		System.out.println("*******************************************");

		
		PrintWriter out = response.getWriter();
		out.println("person.account : "+account+"<br>");
		out.println("person.name    : "+name+"<br>");
	
		return null;   // 傳回 null, 不跳向任何 forwoar

	  } // end if("add".equals(useBeanForm.getAction())){

	  
	  return mapping.getInputForward();  // 傳回輸出頁面
	} // end execute(
	
	
	
	
}