package com.webservice.xfire;
//Generated by MyEclipse

/*
 *  HelloWebService 的實作類別
 */
public class HelloWebServiceImpl implements IHelloWebService {

	
  // 定義服務方法
  public String sayHello(String message) {

	return "Hello,"+message;
  } // end sayHello

	


	
}