/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts1.action;

import java.util.Date;


import java.util.List;

import javax.servlet.http.HttpServletRequest;

import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.util.Assert;

import com.helloweenvsfei.orm.bean.Cat;
import com.helloweenvsfei.orm.dao.ICatService;
import com.helloweenvsfei.struts1.form.Cat2Form;


/** 
 * MyEclipse Struts
 * Creation date: 08-13-2012
 * 
 * XDoclet definition:
 * @struts.action path="/cat2" name="cat2Form" input="/form/listCat2.jsp" scope="request" validate="true"
 */
public class Cat2Action extends Action {
	/*
	 * Generated Methods
	 */

	private ICatService catService;
	

	// Spring 負責注射
    public void setCatService(ICatService catService) {   
		this.catService = catService;
	}


	public ICatService getCatService() {
		return catService;
	}



	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,HttpServletRequest request, HttpServletResponse response) {
		Cat2Form cat2Form = (Cat2Form) form;

		if("add".equals(cat2Form.getAction())){
		  return this.add(mapping,form,request,response);
		}
		return this.list(mapping,form,request,response);
	}  // end ActionForward execute(ActionMapping mapping, ActionForm form,HttpServletRequest request, HttpServletResponse response) 
	
	
	
	
	
	
	private ActionForward add(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response){
		Cat2Form cat2Form = (Cat2Form) form;
		
		Assert.hasLength(cat2Form.getName()," 名字 不能為null");  // 斷言名字非空
		
		Cat cat = new Cat();
		cat.setName(cat2Form.getName());
		cat.setCreateDate(new Date());

	    catService.createCat(cat);                    // 儲存Cat
	    
		return list(mapping,form,request,response);   // 執行 list
	} // end private ActionForward add(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response)
	
	
	
	
	
	private ActionForward list(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response){	
	   List<Cat> catList = catService.listCat();   // 列出所有的 Cat
	   request.setAttribute("catList",catList);    // 將  catList 物件 放入到 request 中
	   
	   return mapping.findForward("list");         // 傳回 list 頁面
	}  // end private ActionForward list(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response){
	
	
}