/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts1.action;

import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.util.Assert;
import org.springframework.web.struts.ActionSupport;

import com.helloweenvsfei.orm.dao.ICatService;
import com.helloweenvsfei.struts1.form.CatForm;
import com.helloweenvsfei.orm.bean.Cat;

/** 
 * MyEclipse Struts
 * Creation date: 08-11-2012
 * 
 * XDoclet definition:
 * @struts.action path="/cat" name="catForm" input="/form/listCat.jsp" scope="request" validate="true"
 * @struts.action-forward name="listCat.jsp" path="/form"
 */

/*
  SpringFramework 提供 ActionSupport 類別來支援 Struts1.X 的 Action。
     繼承了ActionSupport 後就能夠獲得 Spring 的 BeanFactory ，
     從而獲得各種Spring 容器內的各類資源，例如資料來源、Service 物件等。
*/
public class CatAction extends ActionSupport {
	/*
	 * Generated Methods
	 */

	
	// 透過 applicationContext-orm.xml 取得 catService Bean 資源
	// 獲得 Service 物件
	public ICatService getCatServcie(){
	  return (ICatService)getWebApplicationContext().getBean("catService");
	}
	
	
	
	
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	// 主方法
	public ActionForward execute(ActionMapping mapping, ActionForm form,HttpServletRequest request, HttpServletResponse response) {
	  CatForm catForm = (CatForm) form;
		
	  if("add".equals(catForm.getAction())){
		return this.add(mapping,form,request,response);  // 執行 add 方 法
	  }	 
	  return this.list(mapping,form,request,response);   // 執行 list 方法
	} // end public ActionForward execute(ActionMapping mapping, ActionForm form,HttpServletRequest request, HttpServletResponse response) {
	
	
	
	
	
	
	// 執行 add 方 法
	// 增加 Cat 物件
	public ActionForward add(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response){
	  
	  CatForm catForm = (CatForm)form;
	  Assert.hasLength(catForm.getName(),"名字不能為 null"); // 判斷名字非空 
	  
	  
	  Cat cat = new Cat();	
	  cat.setName(catForm.getName());
	  cat.setCreateDate(new Date());
	 
	  ICatService catService = getCatServcie();  // 呼叫 Service 物件
	  catService.createCat(cat);                 // 儲存Cat 物件
	   
	  return this.list(mapping,form,request,response);	 // 執行 list 方法
	} // end public ActionForward add(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response)
	
	
	
	
	
	
	// 執行 list 方法
	// 列出所有 Cat 物件
	public ActionForward list(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse resopnse){	
	  ICatService catService = getCatServcie(); // 呼叫 Service 物件
	  List<Cat> catList = catService.listCat(); // 查詢所有Cat 物件
	  request.setAttribute("catList",catList); // 將所有 cat 物件放入  request 中
	  
	  return mapping.findForward("list");      // 傳回 list 頁面 
	} // end  public ActionForward list(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse resopnse)
	
	
	
	
}