/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-27-2012
 * 
 * XDoclet definition:
 * @struts.form name="catForm"
 */
public class CatForm extends ActionForm {
	
	private String name;    // name ÄÝ©Ê
    private String action;  // action ÄÝ©Ê
	
	

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,HttpServletRequest request) {
		return null;
	}

	
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {

	}

	
	
	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		System.out.println(CatForm.class.getName()+",getName() execte...");
		System.out.println("name = "+name);
		    
		return name;
	}

	
	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
	    System.out.println(CatForm.class.getName()+",setName() execte...");
	    System.out.println("name = "+name);
	    
		this.name = name;
	}


	public String getAction() {
		return action;
	}


	public void setAction(String action) {
		this.action = action;
	}
	
	
	
}